opensearch-project/spring-data-opensearch

README.md
pom.xml
src/main/java/org/opensearch/data/client/orhlc/AbstractOpensearchConfiguration.java
src/main/java/org/opensearch/data/client/orhlc/ClientConfiguration.java
src/main/java/org/opensearch/data/client/orhlc/ClientConfigurationBuilder.java
src/main/java/org/opensearch/data/client/orhlc/CriteriaFilterProcessor.java
src/main/java/org/opensearch/data/client/orhlc/CriteriaQueryProcessor.java
src/main/java/org/opensearch/data/client/orhlc/DefaultClientConfiguration.java
src/main/java/org/opensearch/data/client/orhlc/DefaultClusterOperations.java
src/main/java/org/opensearch/data/client/orhlc/DocumentAdapters.java
src/main/java/org/opensearch/data/client/orhlc/HighlightQueryBuilder.java
src/main/java/org/opensearch/data/client/orhlc/NativeSearchQuery.java
src/main/java/org/opensearch/data/client/orhlc/NativeSearchQueryBuilder.java
src/main/java/org/opensearch/data/client/orhlc/OpensearchAggregations.java
src/main/java/org/opensearch/data/client/orhlc/OpensearchClusterOperations.java
src/main/java/org/opensearch/data/client/orhlc/OpensearchExceptionTranslator.java
src/main/java/org/opensearch/data/client/orhlc/OpensearchRestTemplate.java
src/main/java/org/opensearch/data/client/orhlc/RequestConverters.java
src/main/java/org/opensearch/data/client/orhlc/RequestFactory.java
src/main/java/org/opensearch/data/client/orhlc/ResponseConverter.java
src/main/java/org/opensearch/data/client/orhlc/RestClientFactoryBean.java
src/main/java/org/opensearch/data/client/orhlc/RestClients.java
src/main/java/org/opensearch/data/client/orhlc/RestIndexTemplate.java
src/main/java/org/opensearch/data/client/orhlc/ScriptField.java
src/main/java/org/opensearch/data/client/orhlc/SearchDocumentResponseBuilder.java
src/main/java/org/opensearch/data/client/orhlc/SearchHitsUtil.java

Updates the project to version 0.1.0.
After the update:
```
ls ~/.m2/repository/org/opensearch/spring-data-opensearch/0.1.0-SNAPSHOT
_remote.repositories                              spring-data-opensearch-0.1.0-SNAPSHOT-sources.jar spring-data-opensearch-0.1.0-SNAPSHOT.pom
maven-metadata-local.xml                          spring-data-opensearch-0.1.0-SNAPSHOT.jar
```
Resolves #7 

Baseline the project at version 0.1

---

MAINTAINERS.md

Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>
~I'll work on getting @reta actual maintainer permissions.~
https://github.com/opensearch-project/spring-data-opensearch/invitations

Updated MAINTAINERS.

---

.github/workflows/main_and_pr_workflow.yml
pom.xml
src/test/java/org/opensearch/data/client/EnabledIfOpensearchVersion.java
src/test/java/org/opensearch/data/client/EnabledIfOpensearchVersionCondition.java
src/test/java/org/opensearch/data/client/orhlc/OpensearchORHLCIntegrationTests.java
src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
src/test/resources/testcontainers-opensearch.properties

Add integration tests across the compatibility matrix: 1.3.6, 2.3.0
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/12

Add integration tests across the compatibility matrix

---

settings.gradle.kts

Bump Spring Framework to 6.0.0-RC3
N/A

Bump Spring Framework to 6.0.0-RC3

---

README.md

Update README.md to accomodate latest changes
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/14

Update README.md to accomodate latest changes

---

settings.gradle.kts
src/test/java/org/opensearch/data/client/orhlc/OpenSearchPartQueryORHLCIntegrationTests.java
src/test/java/org/springframework/data/elasticsearch/core/query/ElasticsearchPartQueryIntegrationTests.java

Update Spring Data Elasticsearch to 5.0.0-RC2
N/A

Update Spring Data Elasticsearch to 5.0.0-RC2

---

gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts

Update Spring to 6.0.0-RC4, Gradle to 7.6-rc2
N/A

Update Spring to 6.0.0-RC4, Gradle to 7.6-rc2

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle to 7.6-rc3

---

settings.gradle.kts

Update Spring to 6.0.0

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts

Update Testcontainers to 1.17.6
N/A

Update Testcontainers to 1.17.6

---

settings.gradle.kts

Update Spring Data Elasticsearch to 5.0.0
N/A

Update Spring Data Elasticsearch to 5.0.0

---

.github/workflows/main_and_pr_workflow.yml
gradle.properties
settings.gradle.kts

Update OpenSearch to 2.4.0
N/A

Update OpenSearch to 2.4.0

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle to 7.6-rc-4

---

settings.gradle.kts

Update Jackson to 2.14.1

---

settings.gradle.kts
spring-data-opensearch-examples/spring-boot-gradle/README.md
spring-data-opensearch-examples/spring-boot-gradle/build.gradle.kts
spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/MarketplaceApplication.java
spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/MarketplaceConfiguration.java
spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/model/Product.java
spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/repository/MarketplaceRepository.java
spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/rest/MarketplaceRestController.java
spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/service/MarketplaceInitializer.java
spring-data-opensearch-examples/spring-boot-gradle/src/main/resources/application.yml
spring-data-opensearch-examples/spring-boot-gradle/src/test/java/org/opensearch/data/example/repository/MarketplaceRepositoryIntegrationTests.java

Add examples for using spring-data-opensearch w/o Spring Boot
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/58

Add examples for using spring-data-opensearch w/o Spring Boot

---

README.md

Add a note regarding SNAPSHOTs availability
Part of https://github.com/opensearch-project/spring-data-opensearch/issues/9

Add a note regarding SNAPSHOTs availability

---

settings.gradle.kts

Update Spring Framework to 6.0.2 and Spring Boot to 3.0.0
N/A

Update Spring Framework to 6.0.2 and Spring Boot to 3.0.0

---

RELEASING.md
jenkins/release.jenkinsFile

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Add release documentation and set publishRelease to true
Picked up this releasing.md from other repos in this project. 
[List any issues this PR will resolve]

Add release documentation and set publishRelease to true

---

README.md

Fixing table layout in README.md
N/A

Fixing table layout in README.md

---

.github/workflows/main_and_pr_workflow.yml
settings.gradle.kts

Dependency updates (Spring, JUnit, OpenSearch)
N/A

Dependency updates (Spring, JUnit, OpenSearch)

---

README.md
version.properties

Update README with 0.2.0 release
N/A

Update README with 0.2.0 release

---

README.md
version.properties

Update README.md with 1.0.0 release
https://github.com/opensearch-project/spring-data-opensearch/releases/tag/1.0.0

Update README.md with 1.0.0 release

---

.github/CODEOWNERS

Updated the `CODEOWNERS` file per #95.
Contributes to #95

Updated the CODEOWNERS file to match the MAINTAINERS.md

---

.github/workflows/main_and_pr_workflow.yml
settings.gradle.kts
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/config/nested/EnableNestedRepositoriesIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/config/notnested/EnableRepositoriesIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/LogEntityIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/aggregation/AggregationIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/query/CriteriaQueryIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/repositories/cdi/CdiRepositoryTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/repositories/custommethod/CustomMethodRepositoryIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/repositories/uuidkeyed/UUIDElasticsearchRepositoryIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/repository/query/keywords/QueryKeywordsIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/repository/support/ElasticsearchRepositoryIntegrationTests.java

Routine dependency updates: Spring Framework, Spring Data Elasticsearch, Spring Data Commons
N/A

Routine dependency updates: Spring Framework, Spring Data Elasticsearch, Spring Data Commons

---

settings.gradle.kts

Dependency updates: Spring Boot 3.0.3, Spring Framework 6.0.6, Spring Data Elasticsearch 5.0.3
N/A

Dependency updates: Spring Boot 3.0.4, Spring Framework 6.0.6, Spring Data Elasticsearch 5.0.3

---

README.md
version.properties

Update README.md to mention 1.0.1 release, move next version to 1.0.2
N/A

Update README.md to mention 1.0.1 release, move next version to 1.0.2

---

settings.gradle.kts

Dependency updates: Spring Boot 3.0.5, Spring Data Commons 3.0.4
N/A

Dependency updates: Spring Boot 3.0.5, Spring Data Commons 3.0.4

---

gradle.properties
settings.gradle.kts

Dependency updates: Spring Framework 6.0.8, Spotless 6.18.0, Gradle 8.1
N/A

Dependency updates: Spring Framework 6.0.8, Spotless 6.18.0

---

README.md
version.properties

Update README.md following 1.1.0 release
N/A

Update README.md following 1.1.0 release

---

settings.gradle.kts

Dependency updates: Spring 6.0.9, Spring Data Elasticsearch 5.0.6, Jackson 2.15.1, downgrade Spring Data Commons to 3.0.6
N/A

Dependency updates: Spring Boot 3.0.7, Spring 6.0.9, Spring Data Elasticsearch 5.0.6, Jackson 2.15.1, downgrade Spring Data Commons to 3.0.6

---

.github/workflows/main_and_pr_workflow.yml
README.md
gradle.properties
settings.gradle.kts
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/NativeSearchQueryBuilder.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchRestTemplate.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RequestFactory.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/ResponseConverter.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RestIndexTemplate.java
spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/OpenSearchPartQueryORHLCIntegrationTests.java
spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/RequestFactoryTests.java
version.properties

Compatibility with Spring Boot 3.1.0 and spring-data-elasticsearch 3.1.0
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/134

Compatibility with Spring Boot 3.1.0 and spring-data-elasticsearch 3.1.0

---

.github/workflows/codeql-analysis.yml
.github/workflows/main_and_pr_workflow.yml
.github/workflows/publish-snapshots.yml
settings.gradle.kts

Dependency updates: Spring Boot 3.0.8, Spring 6.0.10, Spring Data Elasticsearch 5.0.7, Jackson 2.15.2, Spring Data Commons to 3.0.7, OpenSearch 2.8.0
N/A

Dependency updates: Spring Boot 3.0.8, Spring 6.0.10, Spring Data Elasticsearch 5.0.7, Jackson 2.15.2, Spring Data Commons to 3.0.7, OpenSearch 2.8.0

---

README.md
version.properties

Update README.md with 1.2.0 release
N/A

Update README.md with 1.2.0 release

---

settings.gradle.kts

Dependency updates: Spring 6.0.11, Spring Data Elasticsearch 5.1.2, Spring Data Commons 3.1.2
N/A

Dependency updates: Spring 6.0.11, Spring Data Elasticsearch 5.1.2, Spring Data Commons 3.1.2

---

settings.gradle.kts

Dependency updates: Spring 6.0.11, Spring Data Elasticsearch 5.0.8, Spring Data Commons 3.0.8
N/A

Dependency updates: Spring 6.0.11, Spring Data Elasticsearch 5.0.8, Spring Data Commons 3.0.8

---

settings.gradle.kts
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RequestConverters.java

Dependency updates: Spring 6.0.12, Spring Data Elasticsearch 5.1.4, Spring Data Commons 3.1.4, JUnit Jupiter 5.10.0
N/A

Dependency updates: Spring 6.0.12, Spring Data Elasticsearch 5.1.4, Spring Data Commons 3.1.4, JUnit Jupiter 5.10.0

---

settings.gradle.kts

Dependency updates: Spring 6.0.12, Spring Data Elasticsearch 5.0.10, Spring Data Commons 3.0.10, JUnit Jupiter 5.10.0
N/A

Dependency updates: Spring 6.0.12, Spring Data Elasticsearch 5.0.10, Spring Data Commons 3.0.10, JUnit Jupiter 5.10.0

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts
settings.gradle.kts

Dependency updates: Jackson 2.15.3, Mockito 5.6.0, Testcontainers 1.19.1, Spring Data Elasticsearch 5.1.5, Spring 6.0.13
N/A

Dependency updates: Jackson 2.15.3, Mockito 5.6.0, Testcontainers 1.19.1, Spring Data Elasticsearch 5.1.5, Spring 6.0.13

---

settings.gradle.kts

Dependency updates: Spring Boot 3.1.5
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/178

Dependency updates: Spring Boot 3.1.5

---

README.md
version.properties

Update README.md and bump the next version
N/A

Update README.md and bump the next version

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts
gradle.properties
settings.gradle.kts

Dependency updates: OpenSearch 2.11.0
N/A

Dependency updates: OpenSearch 2.11.0

---

.github/workflows/main_and_pr_workflow.yml
README.md
buildSrc/src/main/kotlin/java-conventions.gradle.kts
settings.gradle.kts
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchRestTemplate.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RequestFactory.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RestClients.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RestIndexTemplate.java
spring-data-opensearch/src/main/java/org/opensearch/data/core/AbstractIndexTemplate.java
spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/OpenSearchORHLCIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/immutable/ImmutableRepositoryIntegrationTests.java
version.properties

Upgrade to Spring Boot 3.2.0 / Spring Data Elasticsearch 5.2.0
N/A

Upgrade to Spring Boot 3.2.0 / Spring Data Elasticsearch 5.2.0

---

README.md
version.properties

Bump next version to 1.3.1
N/A

Bump next version to 1.3.1

---

settings.gradle.kts

Dependency updates: Spring Boot 3.2.1
N/A

Dependency updates: Spring Boot 3.2.1

---

README.md

Clarify that Spring Data OpenSearch follows the release model of the Spring Data Elasticsearch / Spring Boot projects
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/214

Clarify that Spring Data OpenSearch follows the release model of the Spring Data Elasticsearch / Spring Boot projects

---

gradle/wrapper/gradle-wrapper.properties

Update to Gradle 8.7

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts

Update Testcontainers to 1.19.8
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/237

Update Testcontainers to 1.19.8

---

.github/workflows/main_and_pr_workflow.yml
gradle.properties
settings.gradle.kts

Dependency updates: Spring Framework 6.1.7, OpenSearch 2.14.0
N/A

Dependency updates: Spring Framework 6.1.7, OpenSearch 2.14.0,  Spring Data Elasticsearch 5.2.6

---

settings.gradle.kts

Reverts opensearch-project/spring-data-opensearch#275

Revert "Bump org.springframework.data:spring-data-commons from 3.2.6 to 3.3.0"

---

README.md
spring-data-opensearch-examples/spring-boot-gradle/README.md
spring-data-opensearch-examples/spring-boot-java-client-gradle/README.md

Fix minor issues in README.md files
Follow up https://github.com/opensearch-project/spring-data-opensearch/pull/227 comments 

Fix minor issues in README.md files

---

README.md
version.properties

Update main to 1.4.1
Post 1.4.0 release updates

Update main to 1.4.1

---

README.md
settings.gradle.kts

Dependency updates: Spring Boot 3.3.0
N/A

Dependency updates: Spring Boot 3.3.0

---

settings.gradle.kts

Dependency Updates: Spring Framework 6.1.9, Junit Jupiter 5.10.2, Spring Data Elasticsearch 5.3.1
N/A

Dependency Updates: Spring Framework 6.1.9, Junit Jupiter 5.10.2, Spring Data Elasticsearch 5.3.1

---

settings.gradle.kts

Dependency updates: Spring Boot 3.3.1, Spring Framework 6.1.10
N/A

Dependency updates: Spring Boot 3.3.1, Spring Framework 6.1.10

---

.github/workflows/main_and_pr_workflow.yml
settings.gradle.kts

Dependency updates: Spring Boot 3.2.7, Spring Framework 6.1.10, Spring Data Elasticsearch 5.2.7, Spring Data Commons 3.2.7
N/A

Dependency updates: Spring Boot 3.2.7, Spring Framework 6.1.10, Spring Data Elasticsearch 5.2.7, Spring Data Commons 3.2.7

---

.github/workflows/main_and_pr_workflow.yml

Add branch patterns to CI workflows
Followup on https://github.com/opensearch-project/spring-data-opensearch/pull/292#discussion_r1648193938

Add branch patterns to CI workflows

---

version.properties

Bump next version to 1.5.2
N/A

Bump next version to 1.5.2

---

spring-data-opensearch-examples/spring-boot-gradle/README.md
spring-data-opensearch-examples/spring-boot-gradle/build.gradle.kts
spring-data-opensearch-examples/spring-boot-gradle/src/test/java/org/opensearch/data/example/repository/TestMarketplaceApplication.java

Update example using Testcontainers Service Connection

---

.github/workflows/main_and_pr_workflow.yml
buildSrc/src/main/kotlin/java-conventions.gradle.kts
settings.gradle.kts

Routine dependency updates (Spring, Spring Data Elasticsearch, JUnit, Testcontainers, OpenSearch)
N/A

Routine dependency updates (Spring, Spring Data Elasticsearch, JUnit, Testcontainers, OpenSearch)

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts
settings.gradle.kts

Update Spring Boot to 3.3.3
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/330, https://github.com/opensearch-project/spring-data-opensearch/issues/315

Update Spring Boot to 3.3.3

---

README.md
version.properties

Bump next version to 1.5.3
N/A

Bump next version to 1.5.3

---

gradle/wrapper/gradle-wrapper.properties
settings.gradle.kts

Dependency updates: Spring Data Elasticsearch 5.3.4, Spring Framework 6.1.13, Gradle 8.10.1
N/A

Dependency updates: Spring Data Elasticsearch 5.3.4, Spring Framework 6.1.13, Gradle 8.10.1

---

.github/workflows/main_and_pr_workflow.yml
gradle.properties
settings.gradle.kts

Update to OpenSearch 2.17.0
N/A

Update to OpenSearch 2.17.0

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts
settings.gradle.kts

Dependency updates: Testcontainers 1.20.2, Mockito 5.14.1, JUnit Jupiter 5.11.1, OpenSearch Testcontainers 2.1.1
N/A

Dependency updates: Testcontainers 1.20.2, Mockito 5.14.1, JUnit Jupiter 5.11.1, OpenSearch Testcontainers 2.1.1

---

README.md
version.properties

Bump next version to 1.5.4
N/A

Bump next version to 1.5.4

---

settings.gradle.kts

JUnit Jupiter 5.11.2, Spring Data Elasticsearch 5.3.5, OpenSearch 2.17.1, OpenSearch Java 2.15.0
N/A

Dependency updates: JUnit Jupiter 5.11.2, Spring Data Elasticsearch 5.3.5, OpenSearch 2.17.1, OpenSearch Java 2.15.0

---

README.md
version.properties

Bump next version to 1.5.5
Post 1.5.4 release

Bump next version to 1.5.5

---

README.md
version.properties

Bump next version to 1.6.1
Post 1.6.0 release updates

Bump next version to 1.6.1

---

buildSrc/src/main/kotlin/java-conventions.gradle.kts
settings.gradle.kts

Routine dependency updates
N/A

Routine dependency updates

---

README.md
version.properties

Update next version to 1.6.2
N/A

Update next version to 1.6.2

---

spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/ResponseConverter.java
spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/TypeUtils.java
spring-data-opensearch/src/test/java/org/opensearch/data/client/core/indices/IndexTemplateOperationsOSCIntegrationTests.java

Fixed IndexOperations.getIndexTemplate() logic

---

MAINTAINERS.md

I've only been merging PRs semi-blindly in this repo trying to help @reta out. I'd like to step down from those "responsibilities". Please also remove my maintainer permissions here. Also updated @reta's affiliation.

Step dblock@ down to Emeritus.

---

README.md
version.properties

Update next version to 1.6.3
N/A

Update next version to 1.6.3

---

README.md
spring-data-opensearch-examples/spring-boot-gradle/README.md
spring-data-opensearch-examples/spring-boot-gradle/src/test/java/org/opensearch/data/example/repository/MarketplaceRepositoryIntegrationTests.java
spring-data-opensearch-examples/spring-boot-gradle/src/test/java/org/opensearch/data/example/repository/TestMarketplaceApplication.java
spring-data-opensearch-examples/spring-boot-java-client-gradle/README.md
spring-data-opensearch-examples/spring-boot-java-client-gradle/build.gradle.kts
spring-data-opensearch-examples/spring-boot-java-client-gradle/src/test/java/org/opensearch/data/example/repository/MarketplaceRepositoryIntegrationTests.java
spring-data-opensearch-examples/spring-boot-java-client-gradle/src/test/java/org/opensearch/data/example/repository/TestMarketplaceApplication.java
spring-data-opensearch-testcontainers/src/test/java/org/opensearch/spring/boot/testcontainers/service/connection/OpenSearchContainerConnectionDetailsFactoryIntegrationTests.java
spring-data-opensearch-testcontainers/src/test/java/org/opensearch/spring/boot/testcontainers/service/connection/SecureOpenSearchContainerConnectionDetailsFactoryIntegrationTests.java

see the individual commit messages.
n/a

add example app for java client & update testcontainers to OS 2.19.1

---

settings.gradle.kts

Routing dependency updates: Spring Boot 3.4.4, Spring Framework 6.2.5, JUnit Jupiter 5.12.1
N/A

Routine dependency updates: Spring Boot 3.4.4, Spring Framework 6.2.5, JUnit Jupiter 5.12.2

---

settings.gradle.kts

Update Spring Data Elasticsearch to 5.4.5
N/A

Update Spring Data Elasticsearch to 5.4.5

---

README.md
version.properties

Bump next version to 1.6.4
N/A

Bump next version to 1.6.4

---

README.md

Add documentation section regarding connecting to AWS OpenSearch Serverless services
N/A

Add documentation section regarding connecting to AWS OpenSearch Serverless services

---

README.md

Bump next version to 1.6.5
N/A

Bump next version to 1.6.5

---

README.md
version.properties

Bump next version to 1.7.1
N/A

Bump next version to 1.7.1

---

README.md
version.properties

Bump next version to 1.8.1
N/A

Bump next version to 1.8.1

---

settings.gradle.kts

Update Spring Boot to 3.5.3
See please https://spring.io/blog/2025/06/19/spring-boot-3-5-3-available-now announcement

Update Spring Boot to 3.5.3

---

README.md
version.properties

Bump next version to 1.8.2
N/A

Bump next version to 1.8.2

---

settings.gradle.kts

Update Spring to 6.2.10 and Spring Boot to 3.5.5
N/A

Update Spring to 6.2.10 and Spring Boot to 3.5.5

---

README.md
version.properties

Bump next version to 2.0.2
N/A

Bump next version to 2.0.2

---

README.md
version.properties

Bump next version to 2.0.3
[List any issues this PR will resolve]

Bump next version to 2.0.3

---

README.md
version.properties

Bump next version to 1.8.3
[List any issues this PR will resolve]

Bump next version to 1.8.3
