opensearch-project/spring-data-opensearch

- .github/workflows/codeql-analysis.yml
Fixing CodeQL Github action
See please https://github.com/opensearch-project/spring-data-opensearch/actions/runs/3223598244/jobs/5273846613
> Fixing CodeQL Github action

- pom.xml
Updating spring-data-elasticsearch to 5.0.0-RC1 (released today)
N/A
> Updating spring-data-elasticsearch to 5.0.0-RC1

- MAINTAINERS.md
Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>
Adding @dlvenable to MAITNAINERS unanimously voted in by the existing maintainers for his great early engagement with [a handful of PRs](https://github.com/opensearch-project/spring-data-opensearch/pulls/dlvenable), open issues, code reviews, etc.
> Added David Venable to MAINTAINERS.

- pom.xml
Remove Spring snapshots Apache Maven repository coordinates
Related to https://github.com/opensearch-project/spring-data-opensearch/pull/5
> Remove Spring snapshots Apache Maven repository coordinates

- src/test/java/org/opensearch/data/client/NestedObjectORHLCIntegrationTests.java
- src/test/java/org/springframework/data/elasticsearch/NestedObjectIntegrationTests.java
Remove org.jetbrains.annotations usage in favor of org.springframework.lang.NonNull
N/A
> Remove org.jetbrains.annotations usage in favor of org.springframework.lang.NonNull

- src/main/java/org/opensearch/data/client/orhlc/ClientConfiguration.java
- src/main/java/org/opensearch/data/client/orhlc/DocumentAdapters.java
- src/main/java/org/opensearch/data/client/orhlc/RestClients.java
Running `./gradlew assemble` was failing. The errors reported were issues with Javadocs.
This PR corrects some Javadocs and removes references to Netty.
I plan to create a follow-on PR which includes Gradle `assemble` in the GitHub Actions to validate it continues to work. For now, I've tested via `./gradlew clean assemble` and have a successful build. Also `./gradlew clean build` now succeeds as well.
N/A
> Fixes the Gradle assemble task

- .github/workflows/main_and_pr_workflow.yml
This PR runs the Gradle `assemble` task for pushes to ensure that it continues to run. This PR provides an alternative to #47 .
N/A
> Add an assemble job to the primary GitHub Actions workflow.

- .github/workflows/release-drafter.yml
- jenkins/release.jenkinsFile
This PR adds below things:
* A GitHub action workflow that will be triggered when a tag is pushed to this repository. The workflow builds the release artifacts and creates a draft release with the built artifacts attached as artifacts.tar.gz in the draft release release.
* A jenkins workflow that is triggered based on above draft release. The workflow looks for artifacts.tar.gz, downloads it and then signs it and publishes it to Maven.
Currently, I have kept the autoPublish tab as `false` since this is the first release, we would like to see the staged artifacts before we hit release. Also taking artifacts down from maven is a pain. 
To-Do once the release is successful:
* Change the autoPublish flag to true
* Change the autoRelease tag to true …
> Add release workflows

- README.md
- spring-data-opensearch-test-autoconfigure/build.gradle.kts
- version.properties
Spring Data OpenSearch 0.1.0 is released now: https://repo1.maven.org/maven2/org/opensearch/client/.
Updating README.md with 0.1.0 release and correcting `spring-data-opensearch-test-autoconfigure` artifact name
N/A
> Updating README.md with 0.1.0 release

- .github/workflows/publish-snapshots.yml
- README.md
- RELEASING.md
- buildSrc/src/main/kotlin/java-conventions.gradle.kts
Add workflow to publish snapshots via GHA
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/9
> Add workflow to publish snapshots via GHA

- .github/workflows/main_and_pr_workflow.yml
- README.md
- settings.gradle.kts
- version.properties
Update version to 1.0.0 (prepare for release)
N/A
> Update version to 1.0.0 (prepare for release)

- .github/workflows/release-drafter.yml
This change retrieves the codeowner's list from .github/codeowners file and adds them as approvers for releasing spring-data-opensearch
Here is a sample issue that is created when this workflow runs: https://github.com/gaiksaya/spring-data-opensearch/issues/11
Once approved, the workflow continues to run as usual.
**_Note: This approval duration is subject to the broader 72 hours timeout for a workflow._**
related https://github.com/opensearch-project/opensearch-build/issues/3111
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer …
> Add 2PR approval to release workflow 

- settings.gradle.kts
Dependency updates: Spring Framework 6.0.7, Spring Data Elasticsearch 5.0.4, Jackson 2.14.2, OpenSearch 2.6.0
N/A
> Dependency updates: Spring Framework 6.0.7, Spring Data Elasticsearch 5.0.4, Jackson 2.14.2, OpenSearch 2.6.0

- .github/CODEOWNERS
The `CODEOWNERS` file requires that the owners be on a single line.
See the following discussion for more information: https://github.com/opensearch-project/logstash-output-opensearch/pull/203#discussion_r1142562128
N/A
> Fix the CODEOWNERS file by putting all on a single line.

- README.md
- version.properties
Due to the breaking API changes (see please https://github.com/opensearch-project/spring-data-opensearch/pull/123/files#diff-2667a0376d027f5d9fcdc2606fd50c462c27707c9ca5b4a53d7565c415928364), the new release is required to work with OpenSearch clients 2.7.0+.
N/A
> Prepare for 1.1.0 release, compatible with OpenSearch 2.7.0

- buildSrc/src/main/kotlin/java-conventions.gradle.kts
Fix Maven local repository location (post Gradle 8.4 update)
It seems like Gradle changed `buildDirectory` from `dir` to `property` so it resolved to 
```
./spring-data-opensearch-starter/property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /home/user/spring-data/spring-data-opensearch-parent/build))/repository
```
Failing the release drafter:
```
tar: build: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2
```
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Fix Maven local repository location (post Gradle 8.4 update)

- settings.gradle.kts
Dependency updates: Spring Framework 6.0.14, Spring Data Commons 3.1.6, Spring Data Elasticsearch 5.1.6, Jackson 2.16.0, Spotless 6.22.0
N/A
> Dependency updates: Spring Framework 6.0.14, Spring Data Commons 3.1.6, Spring Data Elasticsearch 5.1.6, Jackson 2.16.0, Spotless 6.22.0

- spring-data-opensearch-examples/spring-boot-gradle/build.gradle.kts
Require Logback 1.4.12 in the Spring Boot example to fix CVE-2023-6378.
Resolves #199
> Logback 1.4.12 in the Spring Boot example to fix CVE-2023-6378

- buildSrc/src/main/kotlin/java-conventions.gradle.kts
Update build to use Gradle 8.5 version catalogs
See please https://docs.gradle.org/8.5/release-notes.html#catalog-precompiled
> Update build to use Gradle 8.5 version catalogs

- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchRestTemplate.java
- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RequestFactory.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/RequestFactoryTests.java
Add refresh policy setting when creating DeleteByQueryRequest
(Is the wait_for option among the refresh options of Delete by query supported? An error occurs when making an actual request. see please opensearch-project/OpenSearch#12687)
See please #244
> Add refresh policy setting when creating DeleteByQueryRequest

- spring-data-opensearch-examples/spring-boot-gradle/src/main/java/org/opensearch/data/example/rest/MarketplaceRestController.java
`@Responsebody` on method, already defined at `@RestController` annotation
n/a
> Remove redundant annotation @ResponseBody

- settings.gradle.kts
Dependency updates: Spring Framework 6.1.6, Spring Data Elasticsearch 3.2.5, Jackson 2.7.0, OpenSearch 2.13.0
N/A
> Dependency updates: Spring Framework 6.1.6, Spring Data Elasticsearch 3.2.5, Jackson 2.7.0, OpenSearch 2.13.0

- spring-data-opensearch/build.gradle.kts
Bump wiremock to 3.6.0
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/273
> Bump wiremock to 3.6.0

- settings.gradle.kts
Dependency updates: Jackson 2.17.1, Opensearch Java 2.10.4
N/A
> Dependency updates: Jackson 2.17.1, Opensearch Java 2.10.4

- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchRestTemplate.java
- spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/OpenSearchTemplate.java
- spring-data-opensearch/src/main/java/org/opensearch/data/core/OpenSearchOperations.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/OpenSearchORHLCSpecificIntegrationTests.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/osc/OpenSearchOSCSpecificIntegrationTests.java
- spring-data-opensearch/src/test/java/org/opensearch/data/core/OpenSearchSpecificIntegrationTests.java
- spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
Enhance Point In Time support with APIs to list active point-in-time searches
Part of https://github.com/opensearch-project/spring-data-opensearch/issues/85
> Enhance Point In Time support with APIs to list active point-in-time searches

- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchExceptionTranslator.java
- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchRestTemplate.java
- spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/OpenSearchTemplate.java
- spring-data-opensearch/src/main/java/org/opensearch/data/core/OpenSearchOperations.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/OpenSearchORHLCSpecificIntegrationTests.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/osc/OpenSearchOSCSpecificIntegrationTests.java
- spring-data-opensearch/src/test/java/org/opensearch/data/core/OpenSearchSpecificIntegrationTests.java
- spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
Backport of https://github.com/opensearch-project/spring-data-opensearch/pull/218 to `1.4.x` line
> [Backport] [1.4.x] Enhance Point In Time support with APIs to list active point-in-time searches (#218)

- buildSrc/src/main/kotlin/java-conventions.gradle.kts
- settings.gradle.kts
Update to Testcontainers 1.20.0 and OpenSearch Testcontainers 2.1.0
N/A
> Update to Testcontainers 1.20.0 and OpenSearch Testcontainers 2.1.0

- README.md
- spring-data-opensearch/build.gradle.kts
Update README.md and fix the `opensearch-rest-client` dependencies. We always need the `opensearch-rest-client`  to be present since `OpenSearchClient`'s default transport is `RestClientTransport`.
Coming from https://github.com/opensearch-project/spring-data-opensearch/issues/267#issuecomment-2239524472
> Update README.md and fix the opensearch-rest-client dependencies

- README.md
- settings.gradle.kts
- spring-data-opensearch-starter/src/main/java/org/opensearch/spring/boot/autoconfigure/OpenSearchConnectionDetails.java
- spring-data-opensearch-starter/src/main/java/org/opensearch/spring/boot/autoconfigure/OpenSearchRestClientAutoConfiguration.java
- spring-data-opensearch-starter/src/main/java/org/opensearch/spring/boot/autoconfigure/OpenSearchRestClientConfigurations.java
- spring-data-opensearch-testcontainers/build.gradle.kts
- spring-data-opensearch-testcontainers/src/main/java/org/opensearch/spring/boot/testcontainers/service/connection/OpenSearchContainerConnectionDetailsFactory.java
- spring-data-opensearch-testcontainers/src/main/resources/META-INF/spring.factories
- spring-data-opensearch-testcontainers/src/test/java/org/opensearch/spring/boot/testcontainers/service/connection/OpenSearchContainerConnectionDetailsFactoryIntegrationTests.java
- spring-data-opensearch-testcontainers/src/test/java/org/opensearch/spring/boot/testcontainers/service/connection/SecureOpenSearchContainerConnectionDetailsFactoryIntegrationTests.java
- spring-data-opensearch-testcontainers/src/test/resources/logback-test.xml
* Add `OpenSearchConnectionDetails`
* Add `PropertiesOpenSearchConnectionDetails` implementation
* Add new module `spring-data-opensearch-testcontainers`
* Add `OpenSearchContainerConnectionDetails` from `OpenSearchContainer`
Previously, `opensearch.uris`, `opensearch.username` and `opensearch.password` had to be declared via `DynamicPropertySource`. Since 3.1, Spring Boot added support for Service Connections, so, nowadays, just adding `@ServiceConnection` to `OpenSearchContainer`, the properties will take values from the container.
N/A
> Add Service Connection support from Testcontainers

- README.md
- settings.gradle.kts
- spring-data-opensearch-docker-compose/build.gradle.kts
- spring-data-opensearch-docker-compose/src/main/java/org/opensearch/spring/boot/docker/compose/service/connection/OpenSearchDockerComposeConnectionDetailsFactory.java
- spring-data-opensearch-docker-compose/src/main/java/org/opensearch/spring/boot/docker/compose/service/connection/OpenSearchEnvironment.java
- spring-data-opensearch-docker-compose/src/main/resources/META-INF/spring.factories
- spring-data-opensearch-docker-compose/src/test/java/org/opensearch/spring/boot/docker/compose/service/connection/OpenSearchDockerComposeConnectionDetailsFactoryTest.java
- spring-data-opensearch-docker-compose/src/test/java/org/opensearch/spring/boot/docker/compose/service/connection/SecureOpenSearchDockerComposeConnectionDetailsFactoryTest.java
- spring-data-opensearch-docker-compose/src/test/resources/org/opensearch/spring/boot/docker/compose/service/connection/opensearch-compose.yaml
- spring-data-opensearch-docker-compose/src/test/resources/org/opensearch/spring/boot/docker/compose/service/connection/secure-opensearch-compose.yaml
Bind containers created from `opensearchproject/opensearch` when compose file is used. `OpenSearchConnectionDetails` is created from the compose file.
Signed-off-by: Eddú Meléndez <eddu.melendez@gmail.com>
> Add Service Connection support from Docker Compose

- spring-data-opensearch-examples/spring-boot-gradle/build.gradle.kts
- spring-data-opensearch-examples/spring-boot-java-client-gradle/build.gradle.kts
Exclude 'opensearch-rest-client-sniffer' from examples since Docker reports non-HTTPs address for container by default
See please https://forum.opensearch.org/t/spring-data-opensearch-example-not-working/17033/3
> Exclude 'opensearch-rest-client-sniffer' from examples since Docker reports non-HTTPs address for container by default

- spring-data-opensearch-examples/spring-boot-gradle/build.gradle.kts
- spring-data-opensearch-examples/spring-boot-java-client-gradle/build.gradle.kts
- spring-data-opensearch-starter/build.gradle.kts
Change dependency configuration of  ``opensearch-rest-client-sniffer`` from implementation to compileOnly
resolve #323 
> Change dependency configuration of ``opensearch-rest-client-sniffer``

- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/RequestFactory.java
- spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/RequestConverter.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/RequestFactoryTests.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/osc/RequestConverterTest.java
Set refresh on DeleteByQueryRequest by DeleteQuery
resolve #335 
> Set refresh on DeleteByQueryRequest by DeleteQuery

- .github/workflows/publish-snapshots.yml
Update the snapshot workflow name to keep it consistent with other repos. This is to ensure the that the critical workflows like `Publish snapshots to maven` are monitored.  Part of https://github.com/opensearch-project/opensearch-build/issues/4941. The monitoring framework monitors the workflows based on the workflow names.
Part of https://github.com/opensearch-project/opensearch-build/issues/4941
> Update the snapshot workflow name

- gradle/wrapper/gradle-wrapper.properties
- spring-data-opensearch/build.gradle.kts
> Update Gradle to 8.11.1

- spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/ResponseConverter.java
- spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
Inconsistency between java client and OpenSearch update by query responses
Closes https://github.com/opensearch-project/spring-data-opensearch/issues/387
> Inconsistency between java client and OpenSearch update by query responses

- buildSrc/src/main/kotlin/java-conventions.gradle.kts
- settings.gradle.kts
Update Spring Boot to 3.4.3 and OpenSearch to 2.19.0 
N/A
>  Update Spring Boot to 3.4.3 and OpenSearch to 2.19.0 

- .github/CODEOWNERS
Removed dblock@ from CODEOWNERS, forgot to do it in #420. 
> Removed dblock@ from CODEOWNERS.

- spring-data-opensearch-examples/spring-boot-gradle/src/test/java/org/opensearch/data/example/repository/MarketplaceRepositoryIntegrationTests.java
- spring-data-opensearch-examples/spring-boot-java-client-gradle/src/test/java/org/opensearch/data/example/repository/MarketplaceRepositoryIntegrationTests.java
the tests of the examples can and should use `ServiceConnection` rather than manually setting the properties. this shows the correct way of using them with `Testcontainers`.
n/a
> use `ServiceConnection` in examples' tests

- settings.gradle.kts
Update Spring Framework to 6.2.7
[CVE-2025-22233](https://spring.io/blog/2025/05/15/spring-framework-6-1-20-and-6-2-7-releases-fix-cve-2025-22233)
> Update Spring Framework to 6.2.7 and Spring Data Elasticsearch to 5.4.6

- .github/workflows/publish-snapshots.yml
- README.md
- RELEASING.md
- buildSrc/src/main/kotlin/java-conventions.gradle.kts
Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration. 
https://central.sonatype.org/publish/publish-portal-snapshots/
We have stored the `onepassword` token in this repo secrets and new credentials for Sonatypes username & password have been stored in `onepassword`.  These credentials will be exported as env variables which used by maven publish.
Part of a campaign issue https://github.com/opensearch-project/opensearch-build/issues/5551
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
> Update the maven snapshot publish endpoint and credential

- spring-data-opensearch/src/main/java/org/opensearch/data/client/orhlc/OpenSearchExceptionTranslator.java
- spring-data-opensearch/src/test/java/org/opensearch/data/client/orhlc/OpenSearchExceptionTranslatorIntegrationTests.java
This PR fixes incorrectly matched index name when translating index not found exception.
N/A
> Extract index name properly when translating not found exception.

- .github/workflows/publish-snapshots.yml
- .github/workflows/release-drafter.yml
- jenkins/release.jenkinsFile
Maven central recently announced the end of life for publishing artifacts via nexus portal. As a part of the migration https://central.sonatype.org/pages/ossrh-eol/#process-to-migrate we made some changes to accommodate the new endpoints. See related [PR](https://github.com/opensearch-project/opensearch-build-libraries/pull/716/files#diff-4a19239627cfa172fa2404fa4a2feb02d26c4e26e1b2125e657d9f48ce4941ed)
Also adds github repository condition for essential workflows else it keeps failing in the fork.
This PR accommodates the change to successfully publish artifacts to maven central in future releases. 
part of https://github.com/opensearch-project/opensearch-build/issues/5552 …
> Update maven publishing workflow to accommodate nexus EOL

- README.md
This change adds a new `JDK Version` column to the compatibility matrix in the documentation of Spring Data OpenSearch. It clarifies the **minimum required JDK version** for each version of the Spring Data OpenSearch library. 
This avoids confusion when users attempt to use incompatible versions (e.g. using Spring Data OpenSearch `2.0.x` with JDK 17, which causes `UnsupportedClassVersionError` due to Java class file version 65).
To verify this requirement, we analyzed the compiled `.class` files using `javap -verbose`, which reveals the bytecode version of the classes:
```bash
/mnt/c/U/o/.m2/r/org/opensearch/client/spring-data-opensearch/2.0.0 ❯ jar xf spring-data-opensearch-2.0.0.jar org/opensearch/data/client/osc/NativeQuery.class …
```
> docs: add JDK compatibility matrix to documentation

- spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/RequestConverter.java
- spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
> [Backport] [1.6.x] don't ignore indices options for multi-search queries

- spring-data-opensearch/src/main/java/org/opensearch/data/client/osc/RequestConverter.java
- spring-data-opensearch/src/test/java/org/springframework/data/elasticsearch/core/ElasticsearchIntegrationTests.java
> [Backport] [1.7.x] don't ignore indices options for multi-search queries

- .github/workflows/main_and_pr_workflow.yml
- buildSrc/src/main/kotlin/java-conventions.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
- spring-data-opensearch-docker-compose/src/test/java/org/opensearch/spring/boot/docker/compose/service/connection/OpenSearchDockerComposeConnectionDetailsFactoryTest.java
- spring-data-opensearch-docker-compose/src/test/java/org/opensearch/spring/boot/docker/compose/service/connection/SecureOpenSearchDockerComposeConnectionDetailsFactoryTest.java
- spring-data-opensearch-docker-compose/src/test/resources/org/opensearch/spring/boot/docker/compose/service/connection/opensearch-compose.yaml
- spring-data-opensearch-docker-compose/src/test/resources/org/opensearch/spring/boot/docker/compose/service/connection/secure-opensearch-compose.yaml
Add JDK-25 to GA and fix integration test runs
N/A
> Add JDK-25 to GA and fix integration test runs
